### ISSUE TITLE
README: update readme

### ISSUE THREAD

**Issue by knpausch** [Eleanorgruth/whats-cookin#119]
- [x] include instructions on how to copy local API server and how to run it (you can use Eleanor's instructions, very helpful)
- [x] Add GIFs to highlight Part 2 functionality
- [x] Highlight Lighthouse Audit in Technology Used
- [x] Update wins to reflect fully tabbable application with focus and 100% pass on Accessibility Audit
- [x] Update context to reflect hours worked in Part 2
- [x] Update abstract to include new user stories from Part 2
- [x] Highlight Agile/Scrum workflow in wins
- [x] Highlight Agile/Scrum workflow in context
- [x] Update wins/challenges

**Comment by jmyacobn** [comment]
Updated all 9 items listed in README!
