### ISSUE TITLE
BUG: Filtering by tag in search bar when you fill in partial parts of the word "SEARCH RESULTS"

### ISSUE THREAD

**Issue by FrazierLE** [Eleanorgruth/whats-cookin#124]

**Comment by Eleanorgruth** [comment]
We might want to talk about this, I was paying around on Target's website and if you search "burrit" all burrito-related items appear. Similarly, if you just search "b" all items starting with the letter b appear. I think that we want the search to be able to search for partial words, we just don't want "B Recipes" to appear at the top of that page. To fix this, I think we could just adjust the text so it says "Search Results" and doesn't interpolate the value from the user input.
