### ISSUE TITLE
REFACTOR: Change verbiage for favorite functionality- USE FAVORITE EVERYWHERE

### ISSUE THREAD

**Issue by Eleanorgruth** [Eleanorgruth/whats-cookin#64]
‘Save it!’ vs ‘Delete Favorite!’ may be confusing to a user, choose either ‘save’ or ‘favorite’ and use it across all verbiage in Part 2.

**Comment by FrazierLE** [comment]
Branch name - refactor/verbiage

**Comment by jmyacobn** [comment]
Resolved during refactor in Part 2
