### ISSUE TITLE
REFACTOR: Tell the user that the recipe was added to favorites

### ISSUE THREAD

**Issue by Eleanorgruth** [Eleanorgruth/whats-cookin#65]
- When I save a recipe, there is no indication to me as the user if it worked when I clicked that button.  And, I can still see and click the “Save It” button for an already-saved recipe which is confusing as a user.  ****
    - **In Part 2, find a way to make it clear to the user if a recipe is already saved and prevent them from clicking on that button for recipes that have already been saved.**  You can decide how to approach this but if you decided to keep button visible even after a recipe has been saved, it should be clear to the user that its disabled and they shouldn’t/can’t click it.

**Comment by jmyacobn** [comment]
Resolved during Part 2 refactor!
