### ISSUE TITLE
REFACTOR: Add a cursor pointer to any clickable elements

### ISSUE THREAD

**Issue by Eleanorgruth** [Eleanorgruth/whats-cookin#66]
Add a cursor pointer to any clickable elements to help indicate that they are clickable.  Consider adding additional indication for when the element has been clicked (especially the buttons that don’t immediately change the user’s view like Save It and Delete).  Think about the apps and websites you use, how can you tell if the button you’re trying to click actually was clicked successfully?

**Comment by jmyacobn** [comment]
Resolved during refactor in Part 2
