### ISSUE TITLE
REFACTOR: show delete favorite button at correct times

### ISSUE THREAD

**Issue by Eleanorgruth** [Eleanorgruth/whats-cookin#67]
Once I saved a recipe, the “Delete Favorite” button showed on any recipe I visited, even though they hadn’t been Saved which is confusing to a user.  In Part 2, refactor this so that the Delete Favorite button only shows when viewing a recipe that is favorited

**Comment by FrazierLE** [comment]
//Only show delete button if the recipe is in the saved recipe array

**Comment by FrazierLE** [comment]
Branch name - refactor/delete-button

**Comment by jmyacobn** [comment]
Resolved during refactor in Part 2
