### ISSUE TITLE
REFACTOR: make the filter radio buttons filter on the click

### ISSUE THREAD

**Issue by Eleanorgruth** [Eleanorgruth/whats-cookin#68]
Ideally, we want the recipes to filter when you click the radio button. However, if this is not an option consider moving the Filter button so it is visible without scrolling.  Currently as a user I was confused why when I selected the Breakfast option, nothing changed.  Because I hadn’t scrolled far enough to see the Filter button

**Comment by FrazierLE** [comment]
// When a radio button is clicked, it should only show the recipes that have that tag associated with them

**Comment by jmyacobn** [comment]
Resolved during refactor in Part 2.
