### ISSUE TITLE
REFACTOR: DRY API calls

### ISSUE THREAD

**Issue by Eleanorgruth** [Eleanorgruth/whats-cookin#70]
- Opportunity to DRY up your apiCalls file.  These 3 functions are identical except the url.  Actually, if you look closely at the url...even that is 90% identical.  **Refactor these 3 functions into 1 dynamic function then use that for all 3 fetch calls.**
    - You’ll also want to add a `.catch()` for any `.then()` to catch errors along the way (not just at the end after the `.then` of the Promise.all

BRANCH: refactor/dry-api-calls
Reviewers: Lauren and Kiko

**Comment by jmyacobn** [comment]
Resolved in refactor for Part 2
