### ISSUE TITLE
Kiko Reminder: After Jen's Refactor: Give User an Error for Unfound Result

### ISSUE THREAD

**Issue by knpausch** [Eleanorgruth/whats-cookin#94]
After we merge Jen's Refactor: Give User an Error for Unfound Result, I can update the nav bar header to be blank or say "Oops!" when user enters an invalid search result

**Comment by jmyacobn** [comment]
Hey Kiko, I am curious about this, as they are getting an error message where the recipes are displayed. Do they need both?

**Comment by jmyacobn** [comment]
The only reason I ask is the user will be looking in that area for results, and if you like, I could append the message above the current display of recipes like I did with favorites page rather than only display the error message.

**Comment by knpausch** [comment]
I just put "Oops!" at the top and they can still see your message in the main display
